version: '3.10'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatroom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password
      TZ: 'Asia/Tehran'

  web:
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8003", "Chatroom.asgi:application"]
    # command: ["gunicorn", "Chatroom.wsgi:application", "--bind", "0.0.0.0:8003"]

    volumes:
      - .:/usr/src/Chatroom
      - ./static:/usr/src/Chatroom/staticfiles
      - ./media:/usr/src/Chatroom/media

    ports:
      - "8003:8003"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:Password@db:5432/chatroom
      - REDIS_URL=redis://redis:6379/0
      # - DJANGO_SETTINGS_MODULE=Chatroom.settings 

  worker:
    build: .
    command: ["celery", "-A", "Chatroom", "worker", "--pool=solo", "--loglevel=info"]
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

volumes:
  postgres_data:
