# Generated by Django 5.0.3 on 2024-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
    ]
