# Generated by Django 5.0.3 on 2024-04-04 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0004_user_bio_alter_user_connections_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pv_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
